nginx:
  image: "nginx:latest"
  links:
    - registry
  ports:
    - "9443:443"
  volumes:
    - "./nginx/nginx.conf:/etc/nginx/conf.d/docker-registry.conf:ro"
    - "./nginx/docker-registry.key:/etc/nginx/docker-registry.key:ro"
    - "./nginx/docker-registry.crt:/etc/nginx/docker-registry.crt:ro"
    - "./nginx/docker-registry.conf:/etc/nginx/docker-registry.conf:ro"
    - "./nginx/docker-registry.htpasswd:/etc/nginx/docker-registry.htpasswd:ro"
  restart: always
registry:
  environment:
    CACHE_REDIS_HOST: redis
    CACHE_REDIS_PORT: 6379
    SEARCH_BACKEND: sqlalchemy
    SETTINGS_FLAVOR: local
    SQLALCHEMY_INDEX_DATABASE: "sqlite:////var/docker-registry-storage/docker-registry.db"
    STORAGE_PATH: /var/docker-registry-storage
  image: "registry:latest"
  restart: always
  links:
    - redis
  volumes:
    - "/var/docker-registry-storage:/var/docker-registry-storage"
redis:
  image: "redis:latest"
  restart: always
